DROP VIEW IF EXISTS "Altium Transducers";
DROP VIEW IF EXISTS "KiCad Switches Pushbuttons";
DROP VIEW IF EXISTS "Altium PPTC Fuses";
DROP VIEW IF EXISTS "KiCad Inductors Power";
DROP VIEW IF EXISTS "Altium Switches Pushbuttons";
DROP VIEW IF EXISTS "Altium Memories";
DROP VIEW IF EXISTS "Altium Capacitors Ceramic 2220";
DROP VIEW IF EXISTS "KiCad Resistors 2220";
DROP VIEW IF EXISTS "KiCad Transducers";
DROP VIEW IF EXISTS "KiCad Resistors 1210";
DROP VIEW IF EXISTS "Altium Optocouplers Digital";
DROP VIEW IF EXISTS "Altium Triacs";
DROP VIEW IF EXISTS "KiCad Switches Switch";
DROP VIEW IF EXISTS "KiCad Oscillator Oscillators";
DROP VIEW IF EXISTS "Altium OpAmps";
DROP VIEW IF EXISTS "KiCad Optocouplers Linear";
DROP VIEW IF EXISTS "Altium Switches Switch";
DROP VIEW IF EXISTS "Altium Diodes Zener";
DROP VIEW IF EXISTS "Altium Diodes TVS";
DROP VIEW IF EXISTS "KiCad Transistors Mosfet";
DROP VIEW IF EXISTS "KiCad Microcontrollers";
DROP VIEW IF EXISTS "KiCad Inductors Chokes";
DROP VIEW IF EXISTS "Altium Resistors 1210";
DROP VIEW IF EXISTS "KiCad Capacitors Ceramic 0603";
DROP VIEW IF EXISTS "Altium Transistors Arrays Mosfet";
DROP VIEW IF EXISTS "KiCad Resistors";
DROP VIEW IF EXISTS "Altium Capacitors Ceramic 0603";
DROP VIEW IF EXISTS "KiCad Potentiometers";
DROP VIEW IF EXISTS "KiCad Optocouplers Digital";
DROP VIEW IF EXISTS "Altium Microcontrollers";
DROP VIEW IF EXISTS "KiCad Capacitors Ceramic 0805";
DROP VIEW IF EXISTS "Altium Potentiometers";
DROP VIEW IF EXISTS "KiCad Crystal Oscillators";
DROP VIEW IF EXISTS "Altium Capacitors Ceramic 1210";
DROP VIEW IF EXISTS "KiCad Transceivers";
DROP VIEW IF EXISTS "KiCad Regulators DCDC";
DROP VIEW IF EXISTS "Altium Ferrite Beads";
DROP VIEW IF EXISTS "KiCad Connectors PCB";
DROP VIEW IF EXISTS "KiCad OpAmps";
DROP VIEW IF EXISTS "Altium Optocouplers Linear";
DROP VIEW IF EXISTS "KiCad PPTC Fuses";
DROP VIEW IF EXISTS "Altium Oscillator Oscillators";
DROP VIEW IF EXISTS "KiCad Capacitors Ceramic";
DROP VIEW IF EXISTS "Altium Transistors Mosfet";
DROP VIEW IF EXISTS "KiCad Discrete Logics";
DROP VIEW IF EXISTS "KiCad Capacitors Electrolytic";
DROP VIEW IF EXISTS "Altium Resistors 0603";
DROP VIEW IF EXISTS "KiCad LED Indicators";
DROP VIEW IF EXISTS "Altium Resistors";
DROP VIEW IF EXISTS "KiCad Capacitors Ceramic 1206";
DROP VIEW IF EXISTS "Altium Capacitors Ceramic 0805";
DROP VIEW IF EXISTS "Altium Capacitors Ceramic";
DROP VIEW IF EXISTS "KiCad Ferrite Beads";
DROP VIEW IF EXISTS "KiCad Transistors BJT";
DROP VIEW IF EXISTS "Altium Capacitors Electrolytic";
DROP VIEW IF EXISTS "KiCad Diodes TVS";
DROP VIEW IF EXISTS "Altium Resistors 0805";
DROP VIEW IF EXISTS "Altium Regulators Linear";
DROP VIEW IF EXISTS "KiCad Resistors 0805";
DROP VIEW IF EXISTS "Altium Crystal Oscillators";
DROP VIEW IF EXISTS "KiCad Diodes Zener";
DROP VIEW IF EXISTS "Altium Discrete Logics";
DROP VIEW IF EXISTS "Altium Capacitors Tantalum";
DROP VIEW IF EXISTS "KiCad Transformers";
DROP VIEW IF EXISTS "Altium Diodes Rectifier";
DROP VIEW IF EXISTS "Altium Transceivers";
DROP VIEW IF EXISTS "Altium Inductors Power";
DROP VIEW IF EXISTS "Altium Resistors 2220";
DROP VIEW IF EXISTS "KiCad Capacitors Ceramic 1210";
DROP VIEW IF EXISTS "KiCad Capacitors Tantalum";
DROP VIEW IF EXISTS "KiCad Resistors 0603";
DROP VIEW IF EXISTS "Altium Transistors BJT";
DROP VIEW IF EXISTS "KiCad Diodes Rectifier";
DROP VIEW IF EXISTS "KiCad Memories";
DROP VIEW IF EXISTS "KiCad Resistors 1206";
DROP VIEW IF EXISTS "KiCad Regulators Linear";
DROP VIEW IF EXISTS "KiCad Transistors Arrays Mosfet";
DROP VIEW IF EXISTS "KiCad Capacitors Ceramic 2220";
DROP VIEW IF EXISTS "Altium Resistors 1206";
DROP VIEW IF EXISTS "Altium Inductors Chokes";
DROP VIEW IF EXISTS "Altium Transformers";
DROP VIEW IF EXISTS "Altium Regulators DCDC";
DROP VIEW IF EXISTS "KiCad Triacs";
DROP VIEW IF EXISTS "Altium Capacitors Ceramic 1206";
DROP VIEW IF EXISTS "Altium Connectors PCB";
DROP VIEW IF EXISTS "Altium LED Indicators";
